### ISSUE TITLE
도메인 일부 수정 필요.

### ISSUE THREAD

**Issue by dongh9508** [perfect-matching/perfectmatching-backend#15]
* `User` 도메인의 password 컬럼은 객체를 반환할 때, 노출되어서는 안되기 때문에 조치가 필요.

*  도메인의 관계성 매핑을 위한  필드 쪽에서 멀티 벨류 필드를 `Set` 컬렉션을 사용할 경우, 객체들을 삽입할 때, 그 객체의 내부 필드 객체가 중복 될 경우, 객체 자체의 중복으로 인지하여 hashCode() 함수를 무한 참조하는 StackOverflow 에러가 발생하므로 조치가 필요. 
  
   * 관련 내용

      > "ID-based equality" means just @EqualsAndHashCode(of="id"). It just says, two objects are equals if they have the same ID. This can be a problem with newly created objects (having no ID yet), etc. It avoids problems with objects changing their state (as the ID never changes, at least for persisted objects) and so changing their hashCode (such a change corrupts any HashMap/Set).

**Comment by ssayebee** [comment]
* 해당 문제점은 HashSet 문제가 아닌 `lombok` 문제로 생각됨.
* `lombok`을 사용하지 않는 경우 해당 문제점이 발생하지 않음.
* **중복**으로 인한 문제점은 아니라고 생각됨.
