### ISSUE TITLE
프로젝트 디테일 페이지에 댓글을 등록하는 `text-area` 태그 생성

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#43]
<img width="968" alt="Screen Shot 2019-08-14 at 7 52 26 PM" src="https://user-images.githubusercontent.com/32382352/63015936-3f3c4b80-becd-11e9-9f54-664b0615e075.png">

- 사진과 같이 추가되었음. 추후 post 부분 구현할때 참고해주세요. 🙂
- p.s. 앞으로 박은빈 팀원이 페이지 변동사항이 생길 때마다 와이어프레임에 반영하기로 함.
- 바뀔때마다 슬랙에 oven.io 주소를 보낼 예정.

**Comment by hagome0** [comment]
확인했습니다. ~

**Comment by donghL-dev** [comment]
확인했습니다.

**Comment by ssayebee** [comment]
확인 했습니다. 해당 이슈를 닫겠습니다.
