### ISSUE TITLE
도메인 추가 및 변경 사항

### ISSUE THREAD

**Issue by ssayebee** [perfect-matching/perfectmatching-backend#55]
## 1. `Project.class`의 변경 사항
* [x] start_date, end_date, deadline 컬럼 삭제
* [x] status Enum Data 수정 (모집중, 진행중, 완료)

## 2. DoneProject 도메인 생성
* [x] 해당 도메인은 완료된 프로젝트의 정보와 외부에서 진행한 프로젝트를 커버하기 위함
* [x] 명세에 따른 생성

## 3. Tag 도메인 생성
* [x] 프로젝트 별 필요 기술을 태깅하고, 태깅 별 검색을 제공하기 위함
* [x] 프로젝트와 M:N 관계성으로 매핑됨

## 4. UserSkill 도메인 생성
* [x] 각 유저들이 보유한 스킬 정보를 담는 도메인

## 5. UsedrSkill 도메인 생성
* [x] DoneProject에 기술 될 스킬 정보를 담는 도메인

**Comment by donghL-dev** [comment]
* [ ]각 생성된 도메인에 따라 테스트 코드도 작성해할 것.
