### ISSUE TITLE
project, doneProject 리스트에 기술 태그 부분 json 데이터  

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#60]
현재 리스트로 받아오는 프로젝트 데이터( project 리스트, doneProject 리스트)의 기술 태그 부분이
json 데이터에 프로퍼티로 있는게 아니라 link 태그로 한번 더 요청을 해서 가져오게 되어있는데, 한번 더 요청하게 하는게 아니라 `tags: [ {idx: 1, text: 스프링}, { idx: 2, text: Node.js}, ... ]` 라는 프로퍼티로 나오게 하는게 더 좋을거 같다.

단일 프로젝트에서 리소스 단위로 요청하는건 얼마 안되서 괜찮치만, 리스트로 보여주는 페이지들은
4개가 있다면 4번요청,  10개씩 불러온다면 10번 요청, 20개씩 불러온다면 20번 요청을 해야되니까 페이지는 한개인데 서버로 요청도 너무 많이가고 버그로 이어질 수 도 있을거 같아서 제안합니다

**Comment by ssayebee** [comment]
관련 내용 확인했습니다. !  생각해보니 말씀하신 방법으로 구현하는게 좋을거 같아요.

**Comment by donghL-dev** [comment]
네, 해당 사항에 맞게 반영하도록 하겠습니다.
