### ISSUE TITLE
로그아웃 시 jwt 만료 방법론

### ISSUE THREAD

**Issue by ssayebee** [perfect-matching/perfectmatching-backend#62]
현재 생성된 token에 user와 관계성을 매핑하여 DB에 저장하고 상태를 나타내는 컬럼을 이용해 해당 토큰의 유효성을 검증하는데, 굳이 모든 토큰들을 DB에 저장할 필요가 없다고 생각됨, 관련 자료를 찾아본 결과 유저가 직접 로그아웃  요청을 한 토큰들에 대해서 블랙리스트를 만들어 관리하는 방법, 엑세스 토큰과 리프레쉬 토큰 두 가지를 이용해 관리 하는 방법 등을 찾을 수 있었음. [관련자료](https://stackoverflow.com/questions/21978658/invalidating-json-web-tokens)

**Comment by donghL-dev** [comment]
블랙리스트로 만들어서 관리하는 방법은 결국 블랙리스트로 보관할 저장소가 필요하지 않을까 싶은데, 구현 방식에 대한 참고 자료도 같이 첨부해주면 좋을것 같습니다. 한번 생성된 토큰에 대해서 액세스 토큰인지 리프레쉬 토큰인지도 결국 DB에 생성된 토큰이 보관이 되어야지 여부를 판별할 수 있을것 같은데, DB에 저장하지 않고 어떤 방식으로 구현하는지에 대한 참고 자료도 첨부 해주셨음 좋겠습니다.
