### ISSUE TITLE
프로젝트 리스트 페이지에서 아이템 가져오는 갯수

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#65]
24개씩 가져오는게 괜찮을거 같습니다~

**Comment by donghL-dev** [comment]
확인했습니다. 다음 반영 때 반영하도록 하겠습니다.

**Comment by KwonYG** [comment]
아 아니다 9개로 일단하자 방금 인피니티 스크롤 구현했는데 24개씩 가져오면 금방끝날거 같다..ㅋㅋ

**Comment by donghL-dev** [comment]
프론트 쪽과 얘기한 후에 12개로 합의보았습니다.

**Comment by KwonYG** [comment]
데이터를 다 가져온 뒤에 리스트페이지로 이동하니 로딩실패가 안뜨네요. 12개로 확정해도 될거같습니다 :)
