### ISSUE TITLE
로그인 요청시 크로스 도메인 문제 발생

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#67]
CORS가 뜨네용

**Comment by ssayebee** [comment]
지금 벌초 중이라 빠른 시일 확인 응답 드리겠습니다.

**Comment by donghL-dev** [comment]
* Spring Security CORS 설정 관련 문제가 있어서 해결했습니다.

  * POSTMAN에서는 안 일어났던 문제라서 클라이언트와 직접 테스트 후에 해결완료.

  * Spring Security 설정에 cors 관련 설정을 추가해주고 CORS 관련 설정을 Bean으로 등록하는 것으로 관련 문제가 해결되었습니다. ([관련자료](https://stackoverflow.com/questions/36968963/how-to-configure-cors-in-a-spring-boot-spring-security-application))

* 해당 이슈에 대한 변경된 부분은 다음 PR 때 반영하도록 하겠습니다.
