### ISSUE TITLE
jwt 토큰에 담기는 정보에 관해서

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#68]
jwt 토큰에서 로그인 유저 정보를 가져오려고 하는데,
`email` 뿐만아니라 `idx`와 `nickname`도 함께 담겨있어야 할거 같습니다.

그리고 유저 정보가 담겨있는 `payload` 부분의 키가 모호한데 사진과 같이 가능한지도 궁금합니다~
<img width="558" alt="Screen Shot 2019-08-31 at 5 19 27 PM" src="https://user-images.githubusercontent.com/32382352/64061298-e6321e80-cc13-11e9-8cb6-212f784ed4b3.png">

**Comment by KwonYG** [comment]
jwt 토큰 디코드 사이트: https://jwt.io/

**Comment by donghL-dev** [comment]
* 해당 부분에 대해 확인했습니다. 제안해주신 부분에 따라서 JWT 토큰의 payload 부분을 다음과 같이 변경하여서 다음 PR 때 반영하도록 하겠습니다.

  ```json
  {
     "iss": "Perfect-Matching Server",
     "aud": "Perfect-Matching Client",
     "sub": "Perfect-Matching JWT Token",
     "idx": 1,
     "email": "test1@email.com",
     "nickname": "testUser_1",
     "iat": 1567254092,
     "exp": 1567254692,
     "role": [
    	"USER"
     ]
  }
  ```
