### ISSUE TITLE
projectDetail 부분 tags 프로퍼티가 빈상태로 날라옴.

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#71]
projectDetail 부분 tags 프로퍼티가 빈상태로 날라옵니다.
혹시 따로 리소스단위로 구현할 계획이 있다면 구현하고나서 명세해주세요~

**Comment by donghL-dev** [comment]
해당 사항 확인 후 다음 PR 때 변경사항을 반영하도록 하겠습니다.

**Comment by ssayebee** [comment]
관련 사항 확인했습니다.
