### ISSUE TITLE
POST 요청시 400 에러

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#74]
POST 요청을 하니 400 에러가 뜨는데, 내가 보내야하는 데이터 포맷 양식 작성해줄수있나?

```javascript
  const result = {
        content: "fewaf",
        designerRecruits: 1,
        developerRecruits: 0,
        etcRecruits: 2,
        location: "부산",
        marketerRecruits: 2,
        plannerRecruits: 1,
        socialUrl: "",
        summary: "awer",
        tags: [],
        title: "feafaew"
      };
```
이렇게 보내는중

**Comment by donghL-dev** [comment]
README에 post 데이터 양식 추가해두었습니다.

**Comment by KwonYG** [comment]
현재 500에러가 나오는중

**Comment by donghL-dev** [comment]
원인이 뭔지 알 것 같네요. 그 부분을 개선해드리겠습니다.

**Comment by ssayebee** [comment]
관련 내용 확인 중, 현재 post 메서드 명세에 혼란될 만한 내용이 있어 알려드립니다. 명세 작성중 optional 한 데이터 (content)가 현재 누락되어 있는데, content는 포함 되어있는게 맞습니다. 관련 부분도 다음 수정에 반영하겠습니다.

**Comment by KwonYG** [comment]
MySQL에서 optional 한 데이터 보낼때 `null`로 보내든, `""` 로 보내든 다 null 들어가게 되나??
그리고 content 넣으면 잘 동작된다는거제??

**Comment by donghL-dev** [comment]
그 넘겨오는 데이터 문제가 아니라 로그인 유저 세션 문제인 것 같아서 그 부분을 다른 로직으로 변경하려고 합니다.

**Comment by KwonYG** [comment]
오키오키

**Comment by ssayebee** [comment]
현재 서버쪽 문제 해결했다고 가정 했을때, 데이터에 content를 넣으시면 되는거 맞습니다. 그리고 `""`, `null` 은 제가 알기론 차이가 있는 부분으로 알고있는데, 확인 후 알려드리겠습니다.

**Comment by donghL-dev** [comment]
에러가 나는 부분의 로직을 변경하였습니다. 프로젝트 post 테스트를 한 번 해보시면 될 것 같습니다.

**Comment by KwonYG** [comment]
구욷

**Comment by donghL-dev** [comment]
* Project 개설시에 프로젝트를 개설하는 유저의 정보를 가져오기 위해서 `@AuthenticationPrincipal` 어노테이션을 이용하여 현재 로그인한 유저의 세션정보로 유저 정보를 가져오려고 했으나 이 부분에서 클라이언트에서 프로젝트 개설 post를 요청할 때 세션에 이상이 생겨서 않아 유저 정보가 `NP` Exception이 나타남.

* 해당 문제를 해결하기 위해서 `@AuthenticationPrincipal` 를 이용해서 유저의 정보를 가져오지 않고 post 요청을 보낼 때 Request 혜더에 담기는 Authorization 헤더에 있는 JWT 토큰 정보를 이용해서 유저 정보를 가져오는 것으로 해당 문제를 해결하였습니다.

* 로직이 변경된 부분은 다음 PR 때 반영하도록 하겠습니다.
