### ISSUE TITLE
`/api/register` POST 데이터 description 부분 GET 요청과 통일

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#75]
유저 프로필을 get 할때는 자기소개 부분이 `summary`라는 이름으로 데이터가 날라오는데,
POST 할때는 description 으로 보내게 되어 있으면 정보수정 로직짤때 복잡해져서 둘중 하나로 통일했으면 좋겠다

**Comment by ssayebee** [comment]
해당 내용 확인 했습니다. 다음 수정에 반영하겠습니다.

**Comment by ssayebee** [comment]
+ summary로 통일 하겠습니다.
