### ISSUE TITLE
`ERR_ADDRESS_UNREACHABLE` 에러 발생

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#79]
서버를 꺼놨거나 포트가 바꼈나요?
리스트 요청이랑 로그인 요청때 아래처럼 에러가 뜨네요

<img width="675" alt="Screen Shot 2019-09-13 at 2 16 51 PM" src="https://user-images.githubusercontent.com/32382352/64839181-7d926b00-d631-11e9-940b-044acd71fc9c.png">

p.s. 추석 다 보내고 고치기

**Comment by donghL-dev** [comment]
확인 결과, 서버컴이 종료되었거나, 네트워크가 끊겨있는 것 같습니다. 서버가 꺼져있는 것이 문제인 것 같습니다. 차후에 점검을 하도록 하겠습니다.

**Comment by donghL-dev** [comment]
해결했습니다.
