### ISSUE TITLE
프로젝트 리스트 쿼리스트링 `ALL` 키워드 제안 

### ISSUE THREAD

**Issue by KwonYG** [perfect-matching/perfectmatching-backend#89]
`project?location=ALL&position=ALL` 쿼리스트링에 ALL 을 넣으면 
사용자 입장에서 전체 메뉴를 선택할 수 도 있고, 분기 처리할 때 경우의 수도 줄어들거 같습니다~

**Comment by donghL-dev** [comment]
확인했습니다. 다음 PR 때 반영하도록 하겠습니다.
