### ISSUE TITLE
프로젝트 개설 로직 오류

### ISSUE THREAD

**Issue by ssayebee** [perfect-matching/perfectmatching-backend#99]
## 프로젝트 개설 페이지

* [x] 현재 모집 인원이 0 명일 경우에도 프로젝트가 정상적으로 개설되는 버그가 있습니다.

* [x] 개발 직군에 기타라는 항목이 있기 때문에, 프로젝트는 최소 1명 이상일 때, 개설 되어야 합니다. 해당 문제점을 해결하고 아래에 댓글을 달아주세요!

**Comment by donghL-dev** [comment]
해당 이슈에 대한 문제를 해결하였습니다. 다음 PR때 변경사항을 반영하도록 하겠습니다.
